<html>

<head>
    <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css"> 
     <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script>
        $(function() {
            var availableTags = [
                "Ellie Goulding",
                "Nirvana",
                "The Fray",
                "Coldplay",
                "Imagine Dragons",
                "Bastille",
                "Eminem",
                "Ben Howard",
                "The Rolling Stones",
                "The Beatles",
                "Led Zeppelin",
                "OneRepublic",
                "Michael Jackson",
                "Jason Derulo",
                "Daughter",
                "Katy Perry",
                "Drake",
                "Calvin Harris",
                "Sam Smith",
                "Of Monsters and Men",
                "Avicii",
                "Sia"
            ];
            $( "#tags" ).autocomplete({
            source: availableTags
            });
        });
    </script>  
    <style>
    a {
        text-decoration: none;
        color: #000000;
    }
    {% block style %}
    {% endblock %}
    </style>
</head>

<body bgcolor="#A4A4A4">

    <div id="wordCloudHeader">
        <h1><a href="http://localhost:3000/">{{ title }}</a><h1>
    </div>

    <div id="wordCloud">
        {% block wordcloud %}{% endblock %}
    </div>

    <div id="artistSearch">
    <div class="ui-widget">
        <form method='get' action='/cloud/new'>
            <input type="text" id="tags" name="artist" placeholder="Enter an artist">
            <br />
            <input type="submit" class="buttons" value="Submit">
            {% block search %}{% endblock %}
        </form>
        {% block addartist %}{% endblock %}
    </div>
    </div>

</body>
</html>