<html>

<head>
    <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css">
    {% block style %} {% endblock %}
</head>

<body bgcolor="#A4A4A4"> <!--gray background -->

    <div id="wordCloudHeader">
        <h1>{{ title }}<h1>
    </div>

    <div id="wordCloud">
        {% block wordcloud %}{% endblock %}
    </div>

    <div id = "artistSearch">
        <form method='get' action='/cloud'>
            <input type="text" name="artist" placeholder="Enter an artist">
            <input type="submit" class="buttons" value="Submit">
        </form>
        {% block search %}{% endblock %}
    </div>

</body>
</html>