<html>

<head>
    <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css">
</head>

<body bgcolor="#A4A4A4">
    <div class="wrapper">
      <div id="lyricsHeader">
         <h1>{{ songtitle }}</h1>
         <h2>{{ artist | raw }}</h2>
      </div>

      <div id = "lyrics">{{ lyrics | raw }}</div>
      <div class="push"></div>
    </div>

    <div class="footer">
      <div>
        <form method='get' action='/songs/{{ word }}'>
          <input type="submit" class="buttons" value="Song Selection">
        </form>
        <form method='get' action='/cloud/back'>
          <input type="submit" class="buttons" VALUE="Word Cloud">
        </form>
      </div>
    </div>

</body>
</html>