<html>

    <head>
        <link rel="stylesheet" type="text/css" href="/Stylesheets/pageStyles.css">
         <style>
            a {
                text-decoration: none;
                color: #000000;
            }
        </style>
    </head>

<body bgcolor="#A4A4A4"> <!--gray background -->
    <div class="wrapper">
        <div id="songHeader">
            <h1>{{ title }}</h1>
            <h2>{{ searchword }}</h2> <!-- VARIABLE -->
        </div>

        <div id = "songTitles">
            <div id="titles">
                Song Title
                <ul>
                {% for song in songs %}
                    <li>
                    <a href="http://localhost:3000/lyrics/{{ song.title }}">{{ song.title }}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>

        <div id = "frequency">
            Frequency
            <ul>
            {% for song in songs %}
                <li>{{ song.frequency }}</li>
            {% endfor %}
            </ul>
       </div>
       <div class="push"></div>
    </div>

    <div class="footer">
        <div>
            <form method='get' action='/cloud'>
                <input type="submit" class="buttons" value="Back">
            </form>
        </div>
    </div>

</body>
</html>