{% extends "homePage.phtml" %}
{% block style %}    <style>
            a {
                text-decoration: none;
                color: #000000;
            }
            #cloud {
                position: relative;
  				top: 50%;
  				transform: translateY(-50%);
  				margin: 0 auto;
            }
    </style>
{% endblock %}
{% block wordcloud %}  
{{cloud|raw}}
{% endblock %}
{% block search %}
{{ parent() }}
<input type="button" class="buttons" value="Add To Cloud" onclick="myFunction()">
{% endblock %}
{% block addartist %}
<script>
  function myFunction() {
    var artist = document.getElementById("artistName").value;
    window.location.href = "http://localhost:3000/cloud?artist=[add]"+artist;
  }
</script>
{% endblock %}

