{% extends "homePage.phtml" %}
{% block style %}
#cloud {
position: relative;
top: 50%;
transform: translateY(-50%);
margin: 0 auto;
}
{% endblock %}
{% block wordcloud %}
{{cloud|raw}}
{% endblock %}
{% block search %}
{{ parent() }}
<input type="button" class="buttons" value="Add To Cloud" onclick="myFunction()">
{% endblock %}
{% block addartist %}
<div class="fb-share-button" data-href = "/test.png" data-layout="button"></div><div id="fb-root"></div>
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

function myFunction() {
  var artist = document.getElementById("artistName").value;
  window.location.href = "http://localhost:3000/cloud/add?artist="+artist;
}

html2canvas(document.getElementById("wordCloud"), {
  onrendered: function(canvas) {
    var image = new Image();
    image.src = canvas.toDataURL("image/png");
    var ajax = new XMLHttpRequest();
    ajax.open("POST", '../imgSave.php',true);
    ajax.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    ajax.send("imgData="+image.src);
    return image; 
  }
});

</script>
{% endblock %}
