{% extends "homePage.phtml" %}
{% block style %}    <style>
            a {
                text-decoration: none;
                color: #000000;
            }
            #cloud {
                position: relative;
  				top: 50%;
  				transform: translateY(-50%);
  				margin: 0 auto;
            }
    </style>
{% endblock %}
{% block wordcloud %}  
{{cloud|raw}}
{% endblock %}
{% block search %}
<!--  this is where add to cloud functionality will be added and fb link
<form id="search" method='get' action='?????'>
    <input type="text" name="firstname" placeholder="Enter an artist">
    <input type="submit" VALUE="Add to Cloud">
</form> -->
{% endblock %}

